# Generated by Django 3.0.8 on 2020-08-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200803_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gotTc',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
