# Generated by Django 3.0.8 on 2020-08-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_student_gottc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='numofsupplies',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
