# Generated by Django 3.0.8 on 2020-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_student_numofsupplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gotTc',
            field=models.BooleanField(default=0),
        ),
    ]
