# Generated by Django 3.0.8 on 2020-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200803_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='finalexams',
            field=models.BooleanField(default=0),
        ),
    ]
